export const stocksSchema = `
  CREATE TABLE IF NOT EXISTS stocks (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit TEXT NOT NULL,
    unitPrice REAL NOT NULL,
    costPrice REAL NOT NULL,
    supplierId TEXT REFERENCES suppliers(id) ON DELETE SET NULL,
    location TEXT,
    sku TEXT,
    status TEXT NOT NULL,
    reorderPoint INTEGER,
    createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
`

export const stocksSeed = [
  {
    id: '1',
    name: 'Steel Sheet',
    description: '1mm thick steel sheet',
    category: 'Raw Materials',
    quantity: 100,
    unit: 'pcs',
    unitPrice: 25.99,
    costPrice: 20.0,
    supplierId: 'sup1',
    location: 'Warehouse A',
    sku: 'STL-001',
    status: 'In Stock',
    reorderPoint: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '2',
    name: 'Circuit Board',
    description: 'Main circuit board for assembly',
    category: 'Components',
    quantity: 50,
    unit: 'pcs',
    unitPrice: 45.99,
    costPrice: 35.0,
    supplierId: 'sup2',
    location: 'Warehouse B',
    sku: 'CIR-001',
    status: 'In Stock',
    reorderPoint: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '3',
    name: 'Aluminum Rod',
    description: '10mm diameter aluminum rod',
    category: 'Raw Materials',
    quantity: 75,
    unit: 'meters',
    unitPrice: 12.5,
    costPrice: 8.75,
    supplierId: 'sup1',
    location: 'Warehouse A',
    sku: 'ALR-003',
    status: 'In Stock',
    reorderPoint: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '4',
    name: 'LED Display',
    description: '7-inch LED display panel',
    category: 'Components',
    quantity: 30,
    unit: 'pcs',
    unitPrice: 85.99,
    costPrice: 65.5,
    supplierId: 'sup3',
    location: 'Warehouse C',
    sku: 'LED-007',
    status: 'Low Stock',
    reorderPoint: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '5',
    name: 'Rubber Gasket',
    description: 'Waterproof rubber gasket',
    category: 'Components',
    quantity: 200,
    unit: 'pcs',
    unitPrice: 2.99,
    costPrice: 1.5,
    supplierId: 'sup4', // Add this supplier in your suppliersSeed
    location: 'Warehouse B',
    sku: 'GSK-021',
    status: 'In Stock',
    reorderPoint: 50,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '6',
    name: 'Power Supply Unit',
    description: '500W power supply unit',
    category: 'Components',
    quantity: 25,
    unit: 'pcs',
    unitPrice: 120.0,
    costPrice: 90.0,
    supplierId: 'sup2',
    location: 'Warehouse C',
    sku: 'PSU-500',
    status: 'In Stock',
    reorderPoint: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '7',
    name: 'Copper Wire',
    description: '2mm copper wire spool',
    category: 'Raw Materials',
    quantity: 40,
    unit: 'spools',
    unitPrice: 35.75,
    costPrice: 28.5,
    supplierId: 'sup5', // Add this supplier too
    location: 'Warehouse A',
    sku: 'CPW-002',
    status: 'In Stock',
    reorderPoint: 12,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '8',
    name: 'Mounting Bracket',
    description: 'Metal mounting bracket for assembly',
    category: 'Components',
    quantity: 60,
    unit: 'pcs',
    unitPrice: 18.25,
    costPrice: 12.75,
    supplierId: 'sup1',
    location: 'Warehouse B',
    sku: 'MBR-045',
    status: 'In Stock',
    reorderPoint: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
]
